name: Sync Fork

on:
  push: # push 时触发, 主要是为了测试配置有没有问题
  schedule:
    - cron: '* */3 * * *' # 每3小时触发, 对于一些更新不那么频繁的项目可以设置为每天一次, 低碳一点
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          github_token: ${{ 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 }}
          owner: kenzok8       # fork 的上游仓库 user
          head: openwrt-packages      # fork 的上游仓库 branch
          base: build-gl.inet/custom/      # 本地仓库 branch

